

name: Add Bills to Splitwise
on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
      
      - name: Get current time
        id: current-date
        uses: josStorer/get-current-time@v2.0.2
        with:
          format: YYYY-MM-DD

      - name: Docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      
      - name: Docker build
        env:
          BUILD_DATE: "${{ steps.current-date.outputs.formattedTime }}"
        run: |
          docker build . --file Dockerfile --tag zeehussain/split-bills:${BUILD_DATE}
      
      - name: Docker push
        if: github.ref == 'refs/heads/main'
        env:
          IMAGE: "zeehussain/split-bills:${{ steps.current-date.outputs.formattedTime }}"
        run: |
          docker push $IMAGE

      - name: Docker run
        uses: addnab/docker-run-action@v3
        env:
          ELEC_PASS: ${{secrets.ELEC_PASS}}
          GAS_PASS: ${{secrets.GAS_PASS}}
          SW_CONSUMER_KEY: ${{secrets.SW_CONSUMER_KEY}}
          SW_CONSUMER_SECRET: ${{secrets.SW_CONSUMER_SECRET}}
          SW_API_KEY: ${{secrets.SW_API_KEY}}
        with: 
          image: zeehussain/split-bills:${{ steps.current-date.outputs.formattedTime }}
      